// Actions Usuários
export const GET_USERS = 'GET_USERS';
export const REGISTER_USERS = 'REGISTER_USERS';
export const DELETE_USERS = 'DELETE_USERS';

// Actions Serviços
export const GET_SERVICES = 'GET_SERVICES';
export const REGISTER_SERVICES = 'REGISTER_SERVICES';
export const DELETE_SERVICES = 'DELETE_SERVICES';

// Actions Atividades
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITIES_ALL = 'GET_ACTIVITIES_ALL';
export const REGISTER_ACTIVITIES = 'REGISTER_ACTIVITIES';
export const DELETE_ACTIVITIES = 'DELETE_ACTIVITIES';

// Actions Equipamentos
export const GET_EQUIPAMENTS = 'GET_EQUIPAMENTS';
export const GET_EQUIPAMENTS_ALL = 'GET_EQUIPAMENTS_ALL';
export const REGISTER_EQUIPAMENTS = 'REGISTER_EQUIPAMENTS';
export const DELETE_EQUIPAMENTS = 'DELETE_EQUIPAMENTS';
