export const LIST_USERS = 'LIST_USERS';
export const LIST_SERVICES = 'LIST_SERVICES';
export const LIST_ACTIVITIES = 'LIST_ACTIVITIES';
export const LIST_ACTIVITIES_ALL = 'LIST_ACTIVITIES_ALL';
export const LIST_EQUIPAMENTS = 'LIST_EQUIPAMENTS';
